include: package:effective_dart/analysis_options.yaml

linter:
  rules:
    public_member_api_docs : false
    constant_identifier_names : false
    prefer_mixin : false
    prefer_relative_imports : false