name: should_have_bought_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.6.0+26

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^4.3.3
  intl: ^0.17.0
  http: ^0.13.0
  syncfusion_flutter_charts: ^19.1.63
  flutter_dotenv: ^3.1.0
  auto_size_text: ^2.1.0
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  google_sign_in: ^5.0.1
  kakao_flutter_sdk: ^0.6.1
  lottie: ^1.0.1
  flutter_easyloading: ^3.0.0
  carousel_slider: ^3.0.0
  emoji_picker_flutter: ^1.0.4
  skeleton_text: ^3.0.0
  url_launcher: ^6.0.6
  admob_flutter: ^1.0.1
  shared_preferences: ^2.0.6
  introduction_screen: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - .env.prod
    - assets/icons/ico_random.png
    - assets/icons/atm_location.png
    - assets/icons/Card.png
    - assets/icons/home.png
    - assets/icons/home_white.png
    - assets/icons/Profile.png
    - assets/icons/ico_loading.png
    - assets/icons/ico_loading_background.png
    - assets/icons/ico_default_profile.png
    - assets/icons/ico_card_up.png
    - assets/icons/ico_card_left.png
    - assets/icons/ico_card_right.png
    - assets/icons/ico_google.png
    - assets/icons/ico_kakao.png
    - assets/lottie/null_animation.json
    - assets/lottie/o_animation.json
    - assets/lottie/x_animation.json
    - assets/images/plus_chick.png
    - assets/images/normal_chick.png
    - assets/images/minus_chick.png
    - assets/icons/ico_heart.png
    - assets/icons/ico_check.png
    - assets/icons/ico_like.png
    - assets/icons/ico_like_small.png
    - assets/icons/ico_like_big.png
    - assets/icons/ico_unlike.png
    - assets/icons/ico_unlike_small.png
    - assets/icons/ico_unlike_big.png
    - assets/icons/ico_search_white.png
    - assets/icons/ico_write.png
    - assets/icons/ico_main_select.png
    - assets/icons/1.5x/ico_main_select.png
    - assets/icons/2x/ico_main_select.png
    - assets/icons/3x/ico_main_select.png
    - assets/icons/4x/ico_main_select.png
    - assets/icons/ico_main_unselect.png
    - assets/icons/1.5x/ico_main_unselect.png
    - assets/icons/2x/ico_main_unselect.png
    - assets/icons/3x/ico_main_unselect.png
    - assets/icons/4x/ico_main_unselect.png
    - assets/icons/ico_card_select.png
    - assets/icons/1.5x/ico_card_select.png
    - assets/icons/2x/ico_card_select.png
    - assets/icons/3x/ico_card_select.png
    - assets/icons/4x/ico_card_select.png
    - assets/icons/ico_card_unselect.png
    - assets/icons/1.5x/ico_card_unselect.png
    - assets/icons/2x/ico_card_unselect.png
    - assets/icons/3x/ico_card_unselect.png
    - assets/icons/4x/ico_card_unselect.png
    - assets/icons/ico_drip_select.png
    - assets/icons/1.5x/ico_drip_select.png
    - assets/icons/2x/ico_drip_select.png
    - assets/icons/3x/ico_drip_select.png
    - assets/icons/4x/ico_drip_select.png
    - assets/icons/ico_drip_unselect.png
    - assets/icons/1.5x/ico_drip_unselect.png
    - assets/icons/2x/ico_drip_unselect.png
    - assets/icons/3x/ico_drip_unselect.png
    - assets/icons/4x/ico_drip_unselect.png
    - assets/icons/ico_word_select.png
    - assets/icons/1.5x/ico_word_select.png
    - assets/icons/2x/ico_word_select.png
    - assets/icons/3x/ico_word_select.png
    - assets/icons/4x/ico_word_select.png
    - assets/icons/ico_word_unselect.png
    - assets/icons/1.5x/ico_word_unselect.png
    - assets/icons/2x/ico_word_unselect.png
    - assets/icons/3x/ico_word_unselect.png
    - assets/icons/4x/ico_word_unselect.png
    - assets/icons/ico_mypage_select.png
    - assets/icons/1.5x/ico_mypage_select.png
    - assets/icons/2x/ico_mypage_select.png
    - assets/icons/3x/ico_mypage_select.png
    - assets/icons/4x/ico_mypage_select.png
    - assets/icons/ico_mypage_unselect.png
    - assets/icons/1.5x/ico_mypage_unselect.png
    - assets/icons/2x/ico_mypage_unselect.png
    - assets/icons/3x/ico_mypage_unselect.png
    - assets/icons/4x/ico_mypage_unselect.png
    - assets/icons/ico_refresh.png
    - assets/icons/1.5x/ico_refresh.png
    - assets/icons/2x/ico_refresh.png
    - assets/icons/3x/ico_refresh.png
    - assets/icons/4x/ico_refresh.png
    - assets/icons/ico_back.png
    - assets/icons/1.5x/ico_back.png
    - assets/icons/2x/ico_back.png
    - assets/icons/3x/ico_back.png
    - assets/icons/4x/ico_back.png
    - assets/icons/ico_back_white.png
    - assets/icons/1.5x/ico_back_white.png
    - assets/icons/2x/ico_back_white.png
    - assets/icons/3x/ico_back_white.png
    - assets/icons/4x/ico_back_white.png
    - assets/icons/ico_random_white.png
    - assets/icons/1.5x/ico_random_white.png
    - assets/icons/2x/ico_random_white.png
    - assets/icons/3x/ico_random_white.png
    - assets/icons/4x/ico_random_white.png
    - assets/icons/ico_search.png
    - assets/icons/1.5x/ico_search.png
    - assets/icons/2x/ico_search.png
    - assets/icons/3x/ico_search.png
    - assets/icons/4x/ico_search.png
    - assets/icons/main_icon.png
    - assets/icons/1.5x/main_icon.png
    - assets/icons/2x/main_icon.png
    - assets/icons/3x/main_icon.png
    - assets/icons/4x/main_icon.png
    - assets/images/image_chick.png
    - assets/images/1.5x/image_chick.png
    - assets/images/2x/image_chick.png
    - assets/images/3x/image_chick.png
    - assets/images/4x/image_chick.png
    - assets/images/guide.png
    - assets/images/1.5x/guide.png
    - assets/images/2x/guide.png
    - assets/images/3x/guide.png
    - assets/images/4x/guide.png
    - assets/images/on_boarding_1.png
    - assets/images/1.5x/on_boarding_1.png
    - assets/images/2x/on_boarding_1.png
    - assets/images/3x/on_boarding_1.png
    - assets/images/4x/on_boarding_1.png
    - assets/images/on_boarding_2.png
    - assets/images/1.5x/on_boarding_2.png
    - assets/images/2x/on_boarding_2.png
    - assets/images/3x/on_boarding_2.png
    - assets/images/4x/on_boarding_2.png
    - assets/images/on_boarding_3.png
    - assets/images/1.5x/on_boarding_3.png
    - assets/images/2x/on_boarding_3.png
    - assets/images/3x/on_boarding_3.png
    - assets/images/4x/on_boarding_3.png
    - assets/images/on_boarding_4.png
    - assets/images/1.5x/on_boarding_4.png
    - assets/images/2x/on_boarding_4.png
    - assets/images/3x/on_boarding_4.png
    - assets/images/4x/on_boarding_4.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
